### PR TITLE
Modified Jenkins file

### PR DESCRIPTION
**Pull request by aliartiza75**

### CODE REVIEW

**Comment by stakater-user** [comment]
@aliartiza75 Yikes! You better fix it before anyone else finds out! [Build 1](https://jenkins.release.stakater.com/job/stakater-lab/job/stakater-nordmart-catalog/job/PR-5/1/) has Failed!

**Comment by stakater-user** [comment]
@aliartiza75 Yikes! You better fix it before anyone else finds out! [Build 2](https://jenkins.release.stakater.com/job/stakater-lab/job/stakater-nordmart-catalog/job/PR-5/2/) has Failed!

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker-release.workshop.stakater.com:443/stakater/catalog:SNAPSHOT-PR-5-4`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker-release.workshop.stakater.com:443/stakater/catalog:SNAPSHOT-PR-5-5`

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker-release.workshop.stakater.com:443/stakater/catalog:SNAPSHOT-PR-5-2`

**Review by hamza3202 — APPROVED** [review]

**Pull request merged**
