### PR TITLE
update-jenkins-config

### PR DESCRIPTION
**Pull request by aliartiza75**
update jenkins config

### CODE REVIEW

**Comment by stakater-user** [comment]
@aliartiza75 Yikes! You better fix it before anyone else finds out! [Build 1](https://jenkins.release.stakater.com/job/stakater-lab/job/stakater-nordmart-catalog/job/PR-15/1/) has Failed!

**Comment by stakater-user** [comment]
@aliartiza75 Yikes! You better fix it before anyone else finds out! [Build 2](https://jenkins.release.stakater.com/job/stakater-lab/job/stakater-nordmart-catalog/job/PR-15/2/) has Failed!

**Comment by stakater-user** [comment]
@aliartiza75 Yikes! You better fix it before anyone else finds out! [Build 2](https://jenkins.delivery.stackator.com/job/stakater-lab/job/stakater-nordmart-catalog/job/PR-15/2/) has Failed!

**Comment by stakater-user** [comment]
@aliartiza75 Image is available for testing. `docker pull docker.delivery.stackator.com:443/stakater-lab/catalog:0.0.0-PR-15-3-SNAPSHOT`

**Review by kahootali — APPROVED** [review]

**Pull request merged**
