### PR TITLE
Add tracing

### PR DESCRIPTION
**Pull request by ahmedwaleedmalik**

### CODE REVIEW

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Yikes! You better fix it before anyone else finds out! [Build 1](https://jenkins.release.stakater.com/job/nordmart-apps/job/stakater-nordmart-catalog/job/PR-29/1/) has Failed!

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Yikes! You better fix it before anyone else finds out! [Build 2](https://jenkins.release.stakater.com/job/nordmart-apps/job/stakater-nordmart-catalog/job/PR-29/2/) has Failed!

**Review by kahootali — DISMISSED** [review]

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Yikes! You better fix it before anyone else finds out! [Build 3](https://jenkins.release.stakater.com/job/nordmart-apps/job/stakater-nordmart-catalog/job/PR-29/3/) has Failed!

**Review by stakater-user — APPROVED** [review]

**Comment by stakater-user** [comment]
@ahmedwaleedmalik Yikes! You better fix it before anyone else finds out! [Build 4](https://jenkins.release.stakater.com/job/nordmart-apps/job/stakater-nordmart-catalog/job/PR-29/4/) has Failed!

**Pull request merged**
