### PR TITLE
Keycloak-integration integration for catalog service

### PR DESCRIPTION
**Pull request by xcrou89**

### CODE REVIEW

**Review by ahmedwaleedmalik — CHANGES_REQUESTED** [review]
Same feedback as:
https://github.com/stakater-lab/stakater-nordmart-cart/pull/26/files#diff-0f6e94db3e0c43a1c0991aeaf7b817a9R13-R15

**Comment by stakater-user** [comment]
@xcrou89 Yikes! You better fix it before anyone else finds out! [Build 1](https://jenkins.release.stakater.com/job/nordmart-apps/job/stakater-nordmart-catalog/job/PR-27/1/) has Failed!

**Comment by stakater-user** [comment]
@xcrou89 Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater-lab/catalog:0.0.0-PR-27-2-SNAPSHOT`

**Comment by stakater-user** [comment]
@xcrou89 Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater-lab/catalog:0.0.0-PR-27-3-SNAPSHOT`

**Comment by stakater-user** [comment]
@xcrou89 Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater-lab/catalog:0.0.0-PR-27-4-SNAPSHOT`

**Comment by stakater-user** [comment]
@xcrou89 Image is available for testing. `docker pull docker.delivery.stakater.com:443/stakater-lab/catalog:0.0.0-PR-27-8-SNAPSHOT`

**Review by ahmedwaleedmalik — APPROVED** [review]

**Pull request merged**
